### PR TITLE
Changed Translations

### PR DESCRIPTION
**Pull request by Thaodan**
Added Translation Label for Cache Settings and updated the english translation.
Added German Translation

### CODE REVIEW

**Comment by tworaz** [comment]
On a side not when the raised issues are fixed I'll also cherry pick the commit to 0.4.x branch. For master it'll probably quickly be incomplete once I start adding new strings to the app. Thaks for the work done so far.

**Comment by Thaodan** [comment]
I hope everything is as you wish, made the suggested changes.

**Comment by tworaz** [comment]
Thank you for for the commit and german translation. As I said I'll merge it to master and cherry pick to 0.4.x branch. This way it should make it to 0.4.2 stable release.

**Comment by Thaodan** [comment]
No Problem tell how I can help you further.

**Comment by tworaz** [comment]
Well, it all depends on what you're good at and what you like doing in your spare time. I won't lie majority of the work that needs doing is connected with coding to some degree. There are some non code related improvements I do have in mind, but there are only a few of those. An example might be creating nicer banner for YTPlayer page in Jolla harbour. The current one is something I've quickly hacked together in a couple of minutes. Some nicer screen shots would also be nice.

**Pull request merged**
