### PR TITLE
Create sv.ts

### PR DESCRIPTION
**Pull request by eson57**
Swedish translation if wanted.

### CODE REVIEW

**Comment by tworaz** [comment]
LGTM, but it'd be nice if you could add an entry for your translation into languages/translations.json. This way it'll appear in translation credits screen and appropriate settings menu.

**Comment by eson57** [comment]
Done! Hope it's ok.  :)

**Comment by tworaz** [comment]
Looks great, thanks for the contribution.

**Comment by eson57** [comment]
Thank you, for making my Jolla so great.  :+1:

**Pull request merged**
