### PR TITLE
Added Russian translation

### PR DESCRIPTION
**Pull request by mentaljam**

### CODE REVIEW

**Comment by tworaz** [comment]
Merged to master as fd0cac837c0ab21ef8b2349df3d1360d6f3a81bc

**Comment by tworaz** [comment]
Thanks for the translation. I'll also cherry pick it to 0.4.x branch so it should make it into 0.4.2 release.

**Comment by mentaljam** [comment]
Thank You for the great app!

**Comment by mentaljam** [comment]
May I ask You to change my reference to "Petr Tsymbarovich <petr@tsymbarovich.ru>" in CREDITS file?

**Comment by tworaz** [comment]
Done. In 0.5.0 I'll add credits section to About page.

**Pull request closed without merging**
